# Generated by Django 6.0.6 on 2026-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_veterinarianprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarianprofile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinarianprofile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='veterinarianprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veterinarianprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='veterinarianprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
