# Generated by Django 6.0.6 on 2026-06-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_veterinarianprofile_clinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarianprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
