# Generated by Django 5.2.5 on 2026-06-11 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_veterinarianprofile_license_number'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarianprofile',
            name='rating_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='VeterinarianReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('rating', models.PositiveSmallIntegerField(db_index=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vet_reviews', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='accounts.veterinarianprofile')),
            ],
            options={
                'db_table': 'users_veterinarianreview',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_rating_range')],
                'unique_together': {('patient', 'appointment')},
            },
        ),
    ]
