# Generated by Django 6.0.6 on 2026-06-11 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('input_type', models.CharField(choices=[('IMAGE', 'Image'), ('SYMPTOM', 'Symptom'), ('BOTH', 'Both')], max_length=20)),
                ('symptom_text', models.TextField(blank=True, null=True)),
                ('predicted_diseases', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], db_index=True, max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('model_version', models.CharField(max_length=20)),
                ('inference_time_ms', models.IntegerField(null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='pets.pet')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnosis_diagnosisrecord',
                'constraints': [models.CheckConstraint(condition=models.Q(('risk_score__range', (0.0, 1.0))), name='chk_risk_score_range')],
            },
        ),
    ]
