"""
Veterinary knowledge base for the 5 supported diseases.
Covers: Skin Infection, Ear Infection, Eye Infection, Parasites, Digestive Issues.

This data is used to:
1. Populate the LLM system prompt
2. Seed the treatments database table
3. Map image classification outputs to disease labels
"""

DISEASES = [
    "Skin Infection",
    "Ear Infection",
    "Eye Infection",
    "Parasites",
    "Digestive Issues",
]

# Maps ViT raw class names -> our 5 standardized disease labels.
IMAGE_CLASS_MAPPING = {
    # ── Skin Infection ──────────────────────────────────────────────────
    "bacterial_dermatosis": "Skin Infection",
    "bacterial dermatosis": "Skin Infection",
    "feline_bacterial_infection": "Skin Infection",
    "fungal_infection": "Skin Infection",
    "fungal infection": "Skin Infection",
    "ringworm": "Skin Infection",
    "malassezia_dermatitis": "Skin Infection",
    "mycetomas": "Skin Infection",
    "sporotrichosis": "Skin Infection",
    "yeast_infection": "Skin Infection",
    "hypersensitivity_allergic_dermatosis": "Skin Infection",
    "allergic_dermatitis": "Skin Infection",
    "hypersensitivity": "Skin Infection",
    "flea_allergy": "Skin Infection",
    "flea allergy": "Skin Infection",
    "solar_dermatitis": "Skin Infection",
    "dermatitis": "Skin Infection",
    "acute_moist_dermatitis": "Skin Infection",
    "pyotraumatic_dermatitis": "Skin Infection",
    "neuro_dermatitis": "Skin Infection",
    "miliary_dermatitis": "Skin Infection",
    "feline_miliary_dermatitis": "Skin Infection",
    "alopecia": "Skin Infection",
    "psychogenic_alopecia": "Skin Infection",
    "stud_tail": "Skin Infection",
    "feline_acne": "Skin Infection",
    "feline acne": "Skin Infection",
    "mange": "Skin Infection",
    "demodicosis": "Skin Infection",
    "demodex": "Skin Infection",
    "demodex_gatoi": "Skin Infection",
    "pemphigus_foliaceus": "Skin Infection",
    "eosinophilic_plaques": "Skin Infection",
    "eosinophilic_plaque": "Skin Infection",
    "rodent_ulcer": "Skin Infection",
    "plasma_cell_pododermatitis": "Skin Infection",
    "cat_bite_abscesses": "Skin Infection",
    "degloving_injuries": "Skin Infection",
    "lacerations": "Skin Infection",
    "surgical_dehiscence": "Skin Infection",
    "thermal_burns": "Skin Infection",
    "hotspot": "Skin Infection",
    "hot_spot": "Skin Infection",
    "basal_cell_tumors": "Skin Infection",
    "fibrosarcoma": "Skin Infection",
    "lipomas": "Skin Infection",
    "mast_cell_tumors": "Skin Infection",
    "squamous_cell_carcinoma": "Skin Infection",
    "cutaneous_herpesvirus": "Skin Infection",
    "horned_paws": "Skin Infection",
    "ingrown_claws": "Skin Infection",
    "onychomycosis": "Skin Infection",
    "paronychia": "Skin Infection",
    "dandruff": "Skin Infection",
    "scales": "Skin Infection",
    "papules": "Skin Infection",
    "pustules": "Skin Infection",
    "lichenification": "Skin Infection",

    # ── Ear Infection ───────────────────────────────────────────────────
    "otitis_externa": "Ear Infection",
    "otitis externa": "Ear Infection",
    "ear_mites": "Ear Infection",
    "ear mites": "Ear Infection",
    "aural_hematoma": "Ear Infection",

    # ── Eye Infection ───────────────────────────────────────────────────
    "conjunctivitis": "Eye Infection",
    "cherry_eye": "Eye Infection",
    "cherry eye": "Eye Infection",
    "uveitis": "Eye Infection",
    "glaucoma": "Eye Infection",
    "cataract": "Eye Infection",
    "iris_atrophy": "Eye Infection",
    "iris atrophy": "Eye Infection",
    "corneal_sequestrum": "Eye Infection",
    "feline_herpesvirus": "Eye Infection",
    "feline_calicivirus": "Eye Infection",
    "chlamydia_felis": "Eye Infection",
    "symblepharon": "Eye Infection",

    # ── Parasites ───────────────────────────────────────────────────────
    "parasitic": "Parasites",
    "flea_allergy_parasites": "Parasites",

    # ── Healthy ─────────────────────────────────────────────────────────
    "healthy": "Healthy",
    "healthy_skin": "Healthy",
}

DISEASE_KNOWLEDGE_BASE = {
    "Skin Infection": {
        "common_in": "Dogs, cats, rabbits — especially breeds with skin folds (Bulldogs, Shar-Peis, Persians)",
        "symptoms": [
            "Redness, inflammation, or hot spots on skin",
            "Itching, scratching, licking, or biting at skin",
            "Hair loss in patches",
            "Scaly, flaky, or crusty skin",
            "Pustules, pimples, or oozing sores",
            "Unusual odor from skin",
            "Thickened or darkened skin (chronic cases)",
        ],
        "treatments": [
            "Medicated shampoos (chlorhexidine, ketoconazole, or benzoyl peroxide)",
            "Topical antibiotic or antifungal creams",
            "Oral antibiotics (vet-prescribed for bacterial infections)",
            "Oral antifungals (vet-prescribed for fungal/ringworm)",
            "Omega-3 fatty acid supplements for skin health",
            "E-collar to prevent licking/scratching",
            "Regular bathing with hypoallergenic shampoo",
            "Elimination diet trial (if allergy suspected)",
        ],
        "vet_urgency": "See vet within 2-3 days if: spreading rapidly, not improving with home care, or showing signs of pain. Emergency if: deep wounds, severe swelling, or fever present.",
    },
    "Ear Infection": {
        "common_in": "Dogs (especially floppy-eared breeds: Cocker Spaniels, Basset Hounds, Golden Retrievers), cats, rabbits",
        "symptoms": [
            "Head shaking or tilting",
            "Scratching or pawing at ears",
            "Brown, yellow, or bloody discharge from ears",
            "Foul odor from ears",
            "Redness or swelling of ear canal",
            "Pain when ears are touched",
            "Crusting or scabs around the ear",
            "Loss of balance (severe inner ear cases)",
        ],
        "treatments": [
            "Vet-prescribed ear drops (antibiotic, antifungal, or steroid)",
            "Regular ear cleaning with vet-approved solution",
            "Keep ears dry — avoid water during baths/swimming",
            "Oral antibiotics or antifungals for severe cases",
            "Pain relief medication (if prescribed by vet)",
            "Address underlying allergies if recurrent",
        ],
        "vet_urgency": "See vet within 24-48 hours. Emergency if: loss of balance, walking in circles, severe pain, or bloody discharge.",
    },
    "Eye Infection": {
        "common_in": "Dogs, cats, rabbits, birds — all species susceptible",
        "symptoms": [
            "Redness or bloodshot eyes",
            "Watery, yellow, or green discharge",
            "Squinting or excessive blinking",
            "Swelling around the eye",
            "Pawing or rubbing at eyes",
            "Cloudiness or film over the eye",
            "Sensitivity to light",
            "Third eyelid visible (cherry eye)",
        ],
        "treatments": [
            "Vet-prescribed antibiotic eye drops or ointment",
            "Saline eye wash to flush debris (sterile, preservative-free)",
            "E-collar to prevent rubbing/scratching",
            "Warm compress to gently clean discharge",
            "Antiviral medication (for feline herpesvirus)",
            "Keep face clean and dry",
            "Artificial tears for lubrication (vet-approved only)",
        ],
        "vet_urgency": "See vet within 24 hours. Emergency if: sudden vision loss, eye protruding, severe swelling, or green/yellow discharge with pain.",
    },
    "Parasites": {
        "common_in": "All pets — dogs, cats, rabbits, birds (external: fleas, ticks, mites; internal: worms, coccidia, giardia)",
        "symptoms": [
            "Visible fleas, ticks, or flea dirt (black specks) in coat",
            "Excessive scratching, biting, or licking",
            "Hair loss, especially at tail base (flea allergy)",
            "Scooting or licking anal area (tapeworms)",
            "Worms visible in stool or vomit",
            "Weight loss despite normal appetite",
            "Bloated/pot-bellied appearance (common in puppies/kittens)",
            "Lethargy and weakness (severe infestations)",
            "Diarrhea (may be bloody with some parasites)",
            "Pale gums (anemia from severe flea/tick infestation)",
        ],
        "treatments": [
            "Species-specific flea/tick preventive (topical or oral — NEVER use dog products on cats)",
            "Deworming medication (pyrantel pamoate, fenbendazole, praziquantel)",
            "Revolution/Stronghold (selamectin — covers many parasites)",
            "Thorough cleaning of bedding and living areas",
            "Vacuum carpets and upholstery daily during infestation",
            "Flea comb regularly to monitor",
            "Probiotics to support gut health after worm treatment",
            "Year-round prevention even for indoor pets",
        ],
        "vet_urgency": "See vet within 1-2 days for confirmed parasites. Emergency if: severe lethargy, pale gums, bloody diarrhea, or visible worms causing blockage.",
    },
    "Digestive Issues": {
        "common_in": "All species — dietary indiscretion is the #1 cause; also stress, infections, toxins, or underlying disease",
        "symptoms": [
            "Vomiting (note: frequency, color, contents)",
            "Diarrhea — watery, bloody, or mucus-containing",
            "Loss of appetite or refusal to eat",
            "Lethargy and depression",
            "Abdominal pain or bloating",
            "Dehydration (check: tacky gums, skin tent test)",
            "Weight loss over time",
            "Excessive drooling or lip-licking (nausea)",
            "Eating grass frantically",
            "Constipation or straining",
        ],
        "treatments": [
            "Withhold food for 12-24 hours (adult pets only — NOT puppies/kittens)",
            "Small amounts of water or ice cubes to prevent dehydration",
            "Bland diet: boiled chicken + white rice (or pumpkin for fiber)",
            "Probiotics formulated for pets",
            "Feed small, frequent meals when reintroducing food",
            "Ensure access to fresh, clean water at all times",
            "Avoid sudden diet changes — transition over 7-10 days",
            "Keep toxic foods out of reach (chocolate, grapes, onions, xylitol)",
        ],
        "vet_urgency": "See vet within 24 hours if: vomiting + diarrhea together, blood in vomit or stool, or lethargy. Emergency if: repeated vomiting (cannot keep water down), suspected toxin ingestion, bloated/distended abdomen, or collapse.",
    },
}
