# Generated by Django 6.0.6 on 2026-06-11 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('gateway', models.CharField(max_length=50)),
                ('gateway_txn_id', models.CharField(max_length=200, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='appointments.appointment')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_amount_positive')],
            },
        ),
    ]
