# Generated by Django 6.0.6 on 2026-06-11 06:05

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='pets.pet')),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments_as_owner', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments_as_vet', to='accounts.veterinarianprofile')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'constraints': [models.CheckConstraint(condition=models.Q(('scheduled_at__gt', django.db.models.functions.datetime.Now())), name='chk_scheduled_future'), models.CheckConstraint(condition=models.Q(('fee_charged__gte', 0)), name='chk_fee_non_negative'), models.CheckConstraint(condition=models.Q(('duration_minutes__in', (15, 30, 45, 60))), name='chk_duration_valid')],
            },
        ),
    ]
