# Generated by Django 5.2.5 on 2026-06-13 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_veterinarianprofile_rating_count_veterinarianreview'),
        ('appointments', '0001_initial'),
        ('pets', '0004_remove_pet_chk_pet_weight_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='chk_duration_valid',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes', 60)), name='chk_duration_valid'),
        ),
    ]
