# Generated by Django 6.0.6 on 2026-06-11 06:05

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('FISH', 'Fish'), ('REPTILE', 'Reptile'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_neutered', models.BooleanField(default=False)),
                ('microchip_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets_pet',
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='chk_pet_weight_positive'), models.CheckConstraint(condition=models.Q(('date_of_birth__lte', django.db.models.functions.datetime.Now())), name='chk_pet_dob_past')],
            },
        ),
    ]
