# Generated by Django 5.2.5 on 2026-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
