# Generated by Django 5.2.5 on 2026-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
