# Generated by Django 5.2.5 on 2026-06-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_allergies'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='chk_pet_weight_positive',
        ),
        migrations.RemoveConstraint(
            model_name='pet',
            name='chk_pet_dob_past',
        ),
    ]
