# Generated by Django 5.2.15 on 2026-06-15 11:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(help_text='Vector embedding stored as JSON array (384 floats).')),
                ('source_type', models.CharField(choices=[('symptom_case', 'Symptom Case'), ('treatment', 'Treatment')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_embeddings',
                'indexes': [models.Index(fields=['source_type'], name='chat_embedd_source__9d8f06_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_age', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('diagnosed', 'Diagnosed'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4000)])),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('symptoms_summary', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='chat.session')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'db_table': 'chat_diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(db_index=True, max_length=100)),
                ('pet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('home_care', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('when_to_see_vet', models.TextField(blank=True, null=True)),
                ('prevention', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_treatments',
                'ordering': ['disease', 'severity'],
                'constraints': [models.UniqueConstraint(fields=('disease', 'pet_type', 'severity'), name='unique_chat_treatment_per_type_severity')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'updated_at'], name='chat_sessio_user_id_9459c6_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['tenant_id'], name='chat_sessio_tenant__16af38_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['session'], name='chat_diagno_session_f9311d_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['disease'], name='chat_diagno_disease_a1e504_idx'),
        ),
    ]
